'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    title: 'Safex',
    subtitle: 'Ultra-Modern Cybersecurity Protection',
    scan_placeholder: 'Enter URL, Phone Number, or UPI ID...',
    scan_button: 'Scan Now',
    risk_score: 'Risk Score',
    safe: 'Safe',
    suspicious: 'Suspicious',
    scam: 'Scam',
    local_processing: 'Local Processing',
    local_processing_desc: 'Data stays on your device and is discarded after analysis.',
    pillars: 'Protection Pillars',
    link_scanner: 'Link Scanner',
    call_verifier: 'Call Verifier',
    msg_analyzer: 'Message Analyzer',
    upi_guard: 'UPI Guard',
    impact: 'Socio-Economic Impact',
    nexus: 'TECH NEXUS | VVCE MYSURU',
    prevented: 'Potential Losses Prevented',
    protected: 'Victims Protected',
    awareness: 'Scam Awareness Module',
    iq_score: 'Scam IQ Score',
    start_test: 'Start Certification Test',
    learn_more: 'Phase 1: Analysis Learn',
    training_active: 'Training Unit Active',
    legal: 'Legitimate',
    scam_detected: 'Scam Attempt',
    next_scenario: 'Next Scenario',
    correct: 'Correct Identification!',
    incorrect: 'You missed the red flags!',
    hero_quote: 'A single link can drain a lifetime of savings.',
    hero_warning: 'SECURE THE NEXT BILLION.',
    stats_label: 'ANNUAL FRAUD COMPLAINTS',
    why_1: 'Personalized Scams',
    why_2: 'Mimicked Identities',
    why_3: 'Trust Exploitation',
    why_4: 'Urgency Pressure',
    why_5: 'Knowledge Gap',
    engine_title: 'UPI GUARD PRO',
    engine_desc: 'Linguistic Manipulation Analysis & Lookalike UPI Verification',
    launch_shield: 'Launch Shield',
    local_badge: 'Local Processing: Zero-Data Privacy',
    slide1_title: 'Vision & The "Safex" Solution',
    slide1_subtitle: 'The Shield Against Digital Fraud',
    slide1_problem: 'Over $12.5B+ is lost annually to phishing, UPI fraud, and social engineering. Most security tools are too technical or reactive, leaving the "human factor" vulnerable.',
    slide1_mission: 'To create a "Digital Immune System" that combines high-fidelity AI detection with immersive education.',
    slide1_innovation: '"Midnight Cyber" Design System—a premium, glassmorphic UI that makes security monitoring intuitive and engaging.',
    slide1_nexus: 'Team Tech Nexus (VVCE Mysuru): Focusing on the complex Indian cybersecurity landscape.',
    slide1_zerotrust: 'Zero-Trust Monitoring: Every link, SMS, and UPI ID is treated as a potential threat.',
    slide1_humancentric: 'Human-Centric Design: Moving beyond blocking tags to active user education.',
    slide2_title: 'Comprehensive Feature Ecosystem',
    slide2_subtitle: 'Multi-Layer Defense for Modern Threats',
    slide2_features: '1. Immersive Scrollytelling • 2. Protection Suite (Link/SMS/UPI Guard) • 3. Real-Time Command Center • 4. Impact Visualizer',
    slide2_links_desc: 'Link Scanner: Deep analysis for homograph attacks and untrusted TLDs (.xyz, .top).',
    slide2_sms_desc: 'SMS Analyzer: AI-driven sentiment analysis to flag high-pressure "Urgency" language.',
    slide2_upi_desc: 'UPI Guard Pro: Proprietary heuristic engine detecting "Lookalike UPI IDs" with 99.8% accuracy.',
    slide3_title: 'Technical Architecture & Backend Flow',
    slide3_subtitle: 'The "Midnight Cyber" Stack',
    slide3_stack: 'Frontend: Next.js 16 (App Router), React 19, TypeScript • Styling: Tailwind CSS 4, Framer Motion.',
    slide3_flow: 'Input ➔ Server Actions ➔ Multi-Engine Analysis (urlscan, VirusTotal, AbuseIPDB, AlienVault) ➔ Core Heuristics ➔ Response <200ms.',
    slide4_title: 'Educational Empowerment (Tell & Test)',
    slide4_subtitle: 'Building the Human Firewall',
    slide4_module: 'Tell & Test Module: A gamified education system that moves beyond warnings to active skill-building.',
    slide4_modes: 'MODE: LEARN (Interactive Cards) • MODE: TEST (Scam IQ Assessment)',
    slide4_regional: 'Regional Inclusivity: Full Bilingual Support (English & Kannada) to empower rural areas.',
    slide4_roadmap: 'Future Roadmap: AI-powered voice scam detection (Vishing) and browser extensions.',
    sos_button: 'SOS PANIC',
    sos_title: 'EMERGENCY RESPONSE FLOW',
    sos_subtitle: 'CRITICAL ACTION REQUIRED',
    sos_step1: 'IMMEDIATE FREEZE',
    sos_step1_desc: 'One-click actions to halt financial damage.',
    sos_call_1930: 'Call 1930 (Helpline)',
    sos_block_upi: 'Block UPI Apps',
    sos_freeze_bank: 'Freeze Bank Accounts',
    sos_step2: 'DIGITAL LOCKDOWN',
    sos_lock_logout: 'Log out of all devices',
    sos_lock_reset: 'Reset Primary Passwords',
    sos_lock_2fa: 'Enable 2FA (MFA)',
    sos_step3: 'EVIDENCE VAULT',
    sos_vault_desc: 'Securely store screenshots and transaction IDs.',
    sos_drop_zone: 'Drag & Drop Screenshots here',
    sos_step4: 'REPORTING ENGINE',
    sos_report_gen: 'Generate Legal Draft',
    sos_report_portal: 'Visit Cyber Portal',
    methodology_on: 'DT Mode: ON',
    methodology_off: 'DT Mode: OFF',
    dt_empathize: 'User-Centric Empathy: Focusing on the human cost of fraud.',
    dt_define: 'Data-Driven Definition: Quantifying the national-scale crisis.',
    dt_sos_rationale: 'Addressing the Deficient Reactive Gap: Providing a safety net when prevention fails.',
  },
  kn: {
    title: 'ಸ್ಕ್ಯಾಮ್‌ಶೀಲ್ಡ್',
    subtitle: 'ಅಲ್ಟ್ರಾ-ಮಾಡರ್ನ್ ಸೈಬರ್ ಸೆಕ್ಯುರಿಟಿ ರಕ್ಷಣೆ',
    scan_placeholder: 'URL, ಫೋನ್ ಸಂಖ್ಯೆ ಅಥವಾ UPI ID ನಮೂದಿಸಿ...',
    scan_button: 'ಈಗ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    risk_score: 'ಅಪಾಯದ ಸ್ಕೋರ್',
    safe: 'ಸುರಕ್ಷಿತ',
    suspicious: 'ಅನುಮಾನಾಸ್ಪದ',
    scam: 'ವಂಚನೆ',
    local_processing: 'ಸ್ಥಳೀಯ ಸಂಸ್ಕರಣೆ',
    local_processing_desc: 'ಡೇಟಾ ನಿಮ್ಮ ಸಾಧನದಲ್ಲಿಯೇ ಇರುತ್ತದೆ ಮತ್ತು ವಿಶ್ಲೇಷಣೆಯ ನಂತರ ಅಳಿಸಲ್ಪಡುತ್ತದೆ.',
    pillars: 'ರಕ್ಷಣಾ ಸ್ತಂಭಗಳು',
    link_scanner: 'ಲಿಂಕ್ ಸ್ಕ್ಯಾನರ್',
    call_verifier: 'ಕಾಲ್ ವೆರಿಫೈಯರ್',
    msg_analyzer: 'ಸಂದೇಶ ವಿಲೇಷಕ',
    upi_guard: 'UPI ಗಾರ್ಡ್',
    impact: 'ಸಾಮಾಜಿಕ-ಆರ್ಥಿಕ ಪ್ರಭಾವ',
    nexus: 'ಟೆಕ್ ನೆಕ್ಸಸ್ | VVCE ಮೈಸೂರು',
    prevented: 'ತಡೆಗಟ್ಟಲಾದ ಸಂಭಾವ್ಯ ನಷ್ಟಗಳು',
    protected: 'ಬಲಿಪಶುಗಳ ರಕ್ಷಣೆ',
    awareness: 'ವಂಚನೆ ಅರಿವು ಮಾಡ್ಯೂಲ್',
    iq_score: 'ವಂಚನೆ ಐಕ್ಯೂ ಸ್ಕೋರ್',
    start_test: 'ಪ್ರಮಾಣೀಕರಣ ಪರೀಕ್ಷೆಯನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    learn_more: 'ಹಂತ 1: ವಿಶ್ಲೇಷಣೆ ಕಲಿಕೆ',
    training_active: 'ತರಬೇತಿ ಯುನಿಟ್ ಸಕ್ರಿಯವಾಗಿದೆ',
    legal: 'ಕಾನೂನುಬದ್ಧವಾಗಿದೆ',
    scam_detected: 'ವಂಚನೆ ತಡೆಗಟ್ಟಲಾಗಿದೆ',
    next_scenario: 'ಮುಂದಿನ ಸನ್ನಿವೇಶ',
    correct: 'ಸರಿಯಾದ ಗುರುತಿಸುವಿಕೆ!',
    incorrect: 'ನೀವು ಕೆಂಪು ಧ್ವಜಗಳನ್ನು ಮಿಸ್ ಮಾಡಿದ್ದೀರಿ!',
    hero_quote: 'ಒಂದು ಸಣ್ಣ ಲಿಂಕ್ ಜೀವಮಾನದ ಉಳಿತಾಯವನ್ನು ಬಲಿತೆಗೆದುಕೊಳ್ಳಬಲ್ಲದು.',
    hero_warning: 'ಮುಂದಿನ ನೂರು ಕೋಟಿ ಜನರಿಗೆ ಭದ್ರತೆ.',
    stats_label: 'ವಾರ್ಷಿಕ ವಂಚನೆ ದೂರುಗಳು',
    why_1: 'ವೈಯಕ್ತಿಕಗೊಳಿಸಿದ ಸ್ಕ್ಯಾಮ್‌ಗಳು',
    why_2: 'ನಕಲಿ ಗುರುತುಗಳು',
    why_3: 'ನಂಬಿಕೆಯ ಶೋಷಣೆ',
    why_4: 'ತುರ್ತು ಒತ್ತಡ',
    why_5: 'ಜ್ಞಾನದ ಕೊರತೆ',
    engine_title: 'UPI ಗಾರ್ಡ್ ಪ್ರೊ',
    engine_desc: 'ಭಾಷಾ ಕುಶಲತೆಯ ವಿಶ್ಲೇಷಣೆ ಮತ್ತು ನಕಲಿ UPI ಪರಿಶೀಲನೆ',
    launch_shield: 'ಶೀಲ್ಡ್ ಲಾಂಚ್ ಮಾಡಿ',
    local_badge: 'ಸ್ಥಳೀಯ ಸಂಸ್ಕರಣೆ: ಶೂನ್ಯ-ಡೇಟಾ ಗೌಪ್ಯತೆ',
    slide1_title: 'ನಮ್ಮ ದೃಷ್ಟಿ ಮತ್ತು ಪರಿಹಾರ',
    slide1_subtitle: 'ಡಿಜಿಟಲ್ ವಂಚನೆ ವಿರುದ್ಧದ ಶೀಲ್ಡ್',
    slide1_problem: 'ವಾರ್ಷಿಕವಾಗಿ ₹1 ಲಕ್ಷ ಕೋಟಿಗೂ ಹೆಚ್ಚು ಹಣ ವಂಚನೆಗೆ ಬಾಲಿಯಾಗುತ್ತಿದೆ ಪ್ರಕ್ರಿಯಾತ್ಮಕ ದೃಷ್ಟಿಕೋನದಿಂದ ಜನಸಾಮಾನ್ಯರಿಗೆ ಭದ್ರತಾ ಸಾಧನಗಳು ತುಂಬಾ ಸಂಕೀರ್ಣವಾಗಿವೆ.',
    slide1_mission: 'ರಿಯಲ್-ಟೈಮ್ AI ಪತ್ತೆಹಚ್ಚುವಿಕೆ ಮತ್ತು ತಲ್ಲೀನಗೊಳಿಸುವ ಶಿಕ್ಷಣದ ಸಮನ್ವಯದ ಮೂಲಕ "ಡಿಜಿಟಲ್ ಇಮ್ಯೂನ್ ಸಿಸ್ಟಮ್" ಅನ್ನು ರಚಿಸುವುದು.',
    slide1_innovation: '"ಮಿಡ್ನೈಟ್ ಸೈಬರ್" ವಿನ್ಯಾಸ ವ್ಯವಸ್ಥೆ—ಗುಣಮಟ್ಟದ, ಗ್ಲಾಸ್ಮಾರ್ಫಿಕ್ UI ಭದ್ರತಾ ಮಾನಿಟರಿಂಗ್ ಅನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತದೆ.',
    slide1_nexus: 'ಟೀಮ್ ಟೆಕ್ ನೆಕ್ಸಸ್ (VVCE ಮೈಸೂರು): ಮೈಸೂರಿನ ಡಿಜಿಟಲ್ ಪರಿಸರದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿದೆ.',
    slide1_zerotrust: 'ಶೂನ್ಯ-ನಂಬಿಕೆ ಮಾನಿಟರಿಂಗ್: ಪ್ರತಿ ಲಿಂಕ್, SMS ಮತ್ತು UPI ಐಡಿಯನ್ನು ಬೆದರಿಕೆಯೆಂದು ಪರಿಗಣಿಸಲಾಗುತ್ತದೆ.',
    slide1_humancentric: 'ಬಳಕೆದಾರ-ಕೇಂದ್ರಿತ ವಿನ್ಯಾಸ: ಕೇವಲ ತಡೆಯುವುದನ್ನು ಮೀರಿ ಬಳಕೆದಾರರ ಜ್ಞಾನ ಹೆಚ್ಚಿಸುವುದು.',
    slide2_title: 'ವೈಶಿಷ್ಟ್ಯಗಳ ಪರಿಸರ ವ್ಯವಸ್ಥೆ',
    slide2_subtitle: 'ಆಧುನಿಕ ಬೆದರಿಕೆಗಳ ವಿರುದ್ಧ ಬಹು-ಪದರದ ರಕ್ಷಣೆ',
    slide2_features: '1. ಸ್ಕ್ರೋಲಿಟೆಲ್ಲಿಂಗ್ • 2. ಪ್ರೊಟೆಕ್ಷನ್ ಸೂಟ್ (ಲಿಂಕ್/SMS/UPI) • 3. ಕಮಾಂಡ್ ಸೆಂಟರ್ • 4. ಇಂಪ್ಯಾಕ್ಟ್ ವಿಚುವಲೈಸರ್',
    slide2_links_desc: 'ಲಿಂಕ್ ಸ್ಕ್ಯಾನರ್: ನಕಲಿ ಅಕ್ಷರಗಳು ಮತ್ತು ಅನುಮಾನಾಸ್ಪದ ಡೊಮೇನ್‌ಗಳ ಪತ್ತೆ.',
    slide2_sms_desc: 'SMS ವಿಶ್ಲೇಷಕ: ಒತ್ತಡದ ಅಥವಾ ತುರ್ತು ಭಾಷೆಯನ್ನು ಪತ್ತೆಹಚ್ಚುವ AI ಎಂಜಿನ್.',
    slide2_upi_desc: 'UPI ಗಾರ್ಡ್ ಪ್ರೊ: ನಕಲಿ UPI ಐಡಿಗಳನ್ನು 99.8% ನಿಖರತೆಯೊಂದಿಗೆ ಪತ್ತೆಹಚ್ಚುತ್ತದೆ.',
    slide3_title: 'ತಾಂತ್ರಿಕ ವಿನ್ಯಾಸ ಮತ್ತು ಬ್ಯಾಕೆಂಡ್ ಹರಿವು',
    slide3_subtitle: '"ಮಿಡ್ನೈಟ್ ಸೈಬರ್" ಸ್ಟ್ಯಾಕ್',
    slide3_stack: 'ಫ್ರಂಟ್ ಎಂಡ್: ನೆಕ್ಸ್ಟ್ ಜೆಎಸ್ 16, ರಿಯಾಕ್ಟ್ 19, ಟೈಪ್‌ಸ್ಕ್ರಿಪ್ಟ್ • ಟೈಲ್‌ವಿಂಡ್ 4, ಫ್ರೇಮರ್ ಮೋಷನ್.',
    slide3_flow: 'ಇನ್ಪುಟ್ ➔ ಸರ್ವರ್ ಆಕ್ಷನ್ಸ್ ➔ ಮಲ್ಟಿ-ಎಂಜಿನ್ ವಿಶ್ಲೇಷಣೆ (urlscan, VT, AbuseIPDB) ➔ ಹ್ಯೂರಿಸ್ಟಿಕ್ ಸಿಂಕ್ ➔ ಪ್ರತಿಕ್ರಿಯೆ <200ms.',
    slide4_title: 'ಶೈಕ್ಷಣಿಕ ಸಬಲೀಕರಣ (ಟೇಲ್ & ಟೆಸ್ಟ್)',
    slide4_subtitle: '"ಹ್ಯೂಮನ್ ಫೈರ್ವಾಲ್" ಅನ್ನು ನಿರ್ಮಿಸುವುದು',
    slide4_module: 'ಟೇಲ್ & ಟೆಸ್ಟ್ ಮಾಡ್ಯೂಲ್: ಕೌಶಲ್ಯ ನಿರ್ಮಾಣದ ಗೇಮಿಫೈಡ್ ಶಿಕ್ಷಣ ವ್ಯವಸ್ಥೆ.',
    slide4_modes: 'ಕಲಿಯಿರಿ (ಇಂಟರ್ಯಾಕ್ಟಿವ್ ಕಾರ್ಡ್‌ಗಳು) • ಪರೀಕ್ಷಿಸಿ (ವಂಚನೆ ಐಕ್ಯೂ ಪರೀಕ್ಷೆ)',
    slide4_regional: 'ಪ್ರಾಂತೀಯ ಒಳಗೊಳ್ಳುವಿಕೆ: ಗ್ರಾಮೀಣ ಜನರನ್ನು ಸಬಲೀಕರಣಗೊಳಿಸಲು ಪೂರ್ಣ ಕನ್ನಡ ಮತ್ತು ಇಂಗ್ಲಿಷ್ ಬೆಂಬಲ.',
    slide4_roadmap: 'ಭವಿಷ್ಯದ ಯೋಜನೆ: AI ಚಾಲಿತ ಧ್ವನಿ ವಂಚನೆ ಪತ್ತೆ (Vishing) ಮತ್ತು ಬ್ರೌಸರ್ ಎಕ್ಸ್‌ಟೆನ್ಷನ್.',
    slide4_engine_sub: '3D ಹ್ಯೂರಿಸ್ಟಿಕ್ ಪ್ಯಾಕೆಟ್ ಅನಾಲಿಸಿಸ್ ಇಂಜಿನ್',
    slide5_impact_title: 'ಪರಿಣಾಮ: ಸುಸ್ಥಿರ ಅಭಿವೃದ್ಧಿ',
    slide5_sdg3: 'SDG 3: ಉತ್ತಮ ಆರೋಗ್ಯ ಮತ್ತು ಯೋಗಕ್ಷೇಮ (ಹಣಕಾಸಿನ ಒತ್ತಡ ಕಡಿತ)',
    slide5_sdg4: 'SDG 4: ಗುಣಮಟ್ಟದ ಶಿಕ್ಷಣ (ಡಿಜಿಟಲ್ ಸಾಕ್ಷರತೆ ಸಬಲೀಕರಣ)',
    sos_button: 'SOS ಪ್ಯಾನಿಕ್',
    sos_title: 'ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ ವ್ಯವಸ್ಥೆ',
    sos_subtitle: 'ತಕ್ಷಣದ ಕ್ರಮದ ಅವಶ್ಯಕತೆಯಿದೆ',
    sos_step1: 'ತಕ್ಷಣದ ಸ್ಥಗಿತ',
    sos_step1_desc: 'ಹಣಕಾಸಿನ ಹಾನಿಯನ್ನು ತಡೆಯಲು ಒಂದು ಕ್ಲಿಕ್ ಕ್ರಮಗಳು.',
    sos_call_1930: '1930 ಗೆ ಕರೆ ಮಾಡಿ (ಸಹಾಯವಾಣಿ)',
    sos_block_upi: 'UPI ಆಪ್‌ಗಳನ್ನು ನಿರ್ಬಂಧಿಸಿ',
    sos_freeze_bank: 'ಬ್ಯಾಂಕ್ ಖಾತೆಗಳನ್ನು ಸ್ಥಗಿತಗೊಳಿಸಿ',
    sos_step2: 'ಡಿಜಿಟಲ್ ಲಾಕ್‌ಡೌನ್',
    sos_lock_logout: 'ಎಲ್ಲಾ ಸಾಧನಗಳಿಂದ ಲಾಗ್ ಔಟ್ ಮಾಡಿ',
    sos_lock_reset: 'ಪಾಸ್‌ವರ್ಡ್‌ಗಳನ್ನು ಮರುಹೊಂದಿಸಿ',
    sos_lock_2fa: '2FA ಸಕ್ರಿಯಗೊಳಿಸಿ',
    sos_step3: 'ಪುರಾವೆ ಸಂಗ್ರಹಣೆ',
    sos_vault_desc: 'ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ಗಳು ಮತ್ತು ಟ್ರಾನ್ಸಾಕ್ಷನ್ ಐಡಿಗಳನ್ನು ಸುರಕ್ಷಿತವಾಗಿರಿಸಿ.',
    sos_drop_zone: 'ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ಗಳನ್ನು ಇಲ್ಲಿಗೆ ಎಳೆಯಿರಿ',
    sos_step4: 'ವರದಿ ಎಂಜಿನ್',
    sos_report_gen: 'ಕಾನೂನು ಕರಡು ರಚಿಸಿ',
    sos_report_portal: 'ಸೈಬರ್ ಪೋರ್ಟಲ್‌ಗೆ ಭೇಟಿ ನೀಡಿ',
    methodology_on: 'DT ಮೋಡ್: ಆನ್',
    methodology_off: 'DT ಮೋಡ್: ಆಫ್',
    dt_empathize: 'ಬಳಕೆದಾರ-ಕೇಂದ್ರಿತ ಸಹಾನುಭೂತಿ: ವಂಚನೆಯ ಮಾನವ ವೆಚ್ಚದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸುವುದು.',
    dt_define: 'ಡೇಟಾ-ಚಾಲಿತ ವ್ಯಾಖ್ಯಾನ: ರಾಷ್ಟ್ರೀಯ ಮಟ್ಟದ ಬಿಕ್ಕಟ್ಟನ್ನು ಪ್ರಮಾಣೀಕರಿಸುವುದು.',
    dt_sos_rationale: 'ಪ್ರತಿಕ್ರಿಯಾತ್ಮಕ ಅಂತರವನ್ನು ಸರಿಪಡಿಸುವುದು: ತಡೆಗಟ್ಟುವಿಕೆ ವಿಫಲವಾದಾಗ ಸುರಕ್ಷತಾ ಜಾಲವನ್ನು ಒದಗಿಸುವುದು.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
